[package]
name = "rustic"
version = "0.1.0"
edition = "2021"

[dependencies]
dyn-clone = "1.0.9"
image = "0.24.5"
nalgebra = { version = "0.31.4", features = ["rand"] }
rand = "0.8.5"
rayon = "1.6.0"
